### PR TITLE
Add test properties to TC metadata

### PR DESCRIPTION
**Pull request by elv1s42**
This PR implements https://github.com/nunit/teamcity-event-listener/issues/87

### CODE REVIEW

**Comment by elv1s42** [comment]
I created a local package from the source code and tested it, new metadata displayed properly and accessible via TeamCity API

**Comment by NikolayPianikov** [comment]
@elv1s42 Thanks for the PR. Can you send a screenshot with an example of how it is displayed in TeamCity?

**Comment by elv1s42** [comment]
Closing the PR for now as more code changes required. Currently, TC does not receive TestCase and TestFixture properties

**Comment by elv1s42** [comment]
> @elv1s42 Thanks for the PR. Can you send a screenshot with an example of how it is displayed in TeamCity?

@NikolayPianikov , sorry, I missed the question.
The metadata is diaplayed under the test node in TC:
image

It's quite useful to see the default NUnit attribute values (like Description) as well as some custom values that you can add. For example, test metadata like logs and screenshots is displayed nicely too (there is no need to locate the files in build artefacts tab).

The issue that I am dealing with right now is that in some cases the metadata is not attached to the test. It happens for the metadata that is passed together with `[TestCase]` and `[TestFixture]` attributes. I want to deal with this issue first and then creata a new PR.

**Pull request closed without merging**
