### PR TITLE
Integrate chocolatey package creation into build script

### LINKED ISSUE #41: Integrate chocolatey package with the build script
A Chocolatey package now exists for the extension, having been created using the binaries from the 3.5 release. We need to now integrate the creation of the package with the build script for the extension.

See nunit/nunit-console#253 and nunit/nunit-project-loader#8 for more info.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #41 

@NikolayPianikov I'm creating the PR so you can review. We still have unexplained failures in AppVeyor and Travis, similar to the previous PR. Under Appveryor, we have integration test failures and under travis a complete failure of the nuget restore step. I feel like you understand your project better than I and may be able to figure this out.

As for the creation of the chocolatey package, I used the same logic as in the other extensions but did not reorganize the code in the same way. I'll leave it to you to keep it structured as you prefer or change it in the future.

### CODE REVIEW

**Comment by CharliePoole** [comment]
@rprouse Can you suggest what's going wrong with the Travis builds? It started when I upgraded the packages.

**Comment by NikolayPianikov** [comment]
@CharliePoole, I will try to reproduce issue on Linux/mono and hope it helps to find what is wrong

**Comment by NikolayPianikov** [comment]
@CharliePoole looks like there is some problem during resolving dependencies in NUnit package 3.7.x, I've rolled back NUnit to 3.6.1 and it is working now. By the way, this issue is also reproduced in a project from the scratch

**Comment by ChrisMaddock** [comment]
@NikolayPianikov - I believe the issue is caused by this repo downloading too old a version of nuget.exe. build.sh currently downloads v2.8.6, which I don't believe can handle the NUnit v3.7.1 NuGet package correctly.

Try replacing build.ps1 and build.sh with the latest versions from the link below, which download NuGet v4.1.0. (NuGet changed the download link for the latest version, which is why this repo is still fetching v2.8.6!)

https://github.com/cake-build/resources

**Comment by NikolayPianikov** [comment]
@ChrisMaddock thank you, it helps

**Comment by NikolayPianikov** [comment]
@CharliePoole, @ChrisMaddock, mono 3.2.8 still has error and I can't reproduce it locally, do you have any ideas?

**Comment by ChrisMaddock** [comment]
Not sure sorry, we've dropped mono 3.2.8 support on the main projects.

**Comment by ChrisMaddock** [comment]
Travis has recently upgraded the default Unix environment to Trusty - and looks like the package can't be found there? Maybe try adding `dist: precise` to the .travis.yml? (Or just dropping 3.2.8...that would be my preference! ;-) )

**Comment by CharliePoole** [comment]
I got rid of mono 3.28, consistent with what we are doing with other projects. Travic-ci now passes.

We still have a failing integration test in the AppVeyor pr build. What do you want to do?

**Comment by NikolayPianikov** [comment]
@CharliePoole I will ignore test while I do not find a problem

**Comment by NikolayPianikov** [comment]
@CharliePoole don't you have any objections to merge PR?

**Pull request merged**
